import { type ReactElement, useState } from 'react';
import type ScribePlugin from 'src';
import {
  LanguageDisplayNames,
  LanguageOptions,
  type OutputLanguageOptions,
} from 'src/util/consts';
import DirectorySelect from './DirectorySelect';
import { AudioDeviceSettings } from './components/AudioDeviceSettings';
import {
  SettingsInput,
  SettingsSelect,
  SettingsToggle,
} from './components/SettingsControl';
import { SettingsItemHeader } from './components/SettingsItem';
import { OBSIDIAN_PATHS, type ScribePluginSettings } from './settings';
import useSettingsForm from './useSettingsForm';

const languagesMapping = Object.entries(LanguageDisplayNames)
  .filter(([value]) => value !== LanguageOptions.auto)
  .map(([value, displayName]) => ({ displayName, value }));

/**
 * Tab, containing general settings
 */
function GeneralSettingsTab() {
  const { register } = useSettingsForm();

  return (
    <div>
      <SettingsItemHeader name="Audio" />
      {/* <AudioDeviceSettings plugin={plugin} saveSettings={saveSettings} /> */}
      <SettingsItemHeader name="AI Processing" />
      <SettingsToggle
        {...register('isDisableLlmTranscription', {
          // Inverted displayed value because initial semantics was misleading
          // Old: negative meaning (disable) => Truthy toggle state
          // New: positive meaning (enable) => Truthy toggle state
          displayValue: (value) => !value,
          setValueAs: (value) => !value,
        })}
        name="Recordings transcription"
        description="If disabled, audio will not be sent to any LLM for transcription"
      />
      <SettingsToggle
        {...register('isOnlyTranscribeActive', {
          // Inverted displayed value because initial semantics was misleading
          // Old: negative meaning (disable) => Truthy toggle state
          // New: positive meaning (enable) => Truthy toggle state
          displayValue: (value) => !value,
          setValueAs: (value) => !value,
        })}
        name="Transcription LLM processing & synthesis"
        description="If disabled, we will only transcribe recordings without summarization, insights etc."
      />

      <SettingsItemHeader name="Language" />
      <SettingsSelect
        {...register('scribeOutputLanguage')}
        name="Scribe output language"
        description="The language for the notes generated by Scribe to be in"
        valuesMapping={languagesMapping}
      />
      <SettingsSelect
        {...register('audioFileLanguage')}
        name="Spoken language"
        description="The default spoken language for audio transcription, 
          changing from auto may increase accuracy"
        valuesMapping={languagesMapping}
      />

      <SettingsItemHeader name="Transcripts" />
      <DirectorySelect
        {...register('transcriptDirectory')}
        name="Directory for transcripts"
      />
      <SettingsToggle
        name='Link to Scribe in "created_by" frontmatter'
        description="If true, we will add a link to the Scribe in the frontmatter of the note.  This is useful for knowing which notes were created by Scribe."
        {...register('isFrontMatterLinkToScribe', {
          displayValue: (value) => !value,
          setValueAs: (value) => !value,
        })}
      />
      <SettingsInput
        {...register('noteFilenamePrefix')}
        name="Transcript filename prefix"
        description="This will be the prefix of the note filename, use {{date}} to include the date"
        placeholder="scribe-"
      />

      <SettingsItemHeader name="Recordings" />
      <DirectorySelect
        {...register('recordingDirectory')}
        name="Directory for recordings"
      />
    </div>
  );
}

export default GeneralSettingsTab;
